name: ff_source_code
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_links: 3.4.1
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  cloud_firestore: 4.8.0
  cloud_firestore_platform_interface: 5.15.0
  cloud_firestore_web: 3.6.0
  cloud_functions: 4.3.2
  cloud_functions_platform_interface: 5.4.2
  cloud_functions_web: 4.5.2
  equatable: 2.0.5
  file_picker: 5.2.6
  firebase_auth: 4.6.2
  firebase_auth_platform_interface: 6.15.2
  firebase_auth_web: 5.5.2
  firebase_core: 2.13.1
  firebase_core_platform_interface: 4.8.0
  firebase_core_web: 2.5.0
  firebase_messaging: 14.6.2
  firebase_messaging_platform_interface: 4.5.2
  firebase_messaging_web: 3.5.2
  firebase_storage: 11.2.2
  firebase_storage_platform_interface: 4.4.2
  firebase_storage_web: 3.6.2
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  flutter_plugin_android_lifecycle: 2.0.9
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  functions_client: 1.3.2
  go_router: 7.1.1
  google_fonts: 4.0.3
  google_sign_in: 6.0.2
  google_sign_in_android: 6.1.8
  google_sign_in_ios: 5.6.1
  google_sign_in_platform_interface: 2.4.0
  google_sign_in_web: 0.11.0+2
  gotrue: 1.11.0
  hive: 2.2.3
  image_picker: 1.0.4
  image_picker_android: 0.8.8
  image_picker_for_web: 3.0.1
  image_picker_ios: 0.8.8+2
  image_picker_platform_interface: 2.9.1
  intl: 0.18.0
  json_path: 0.6.2
  mime_type: 1.0.0
  page_transition: 2.0.4
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  plugin_platform_interface: 2.1.3
  postgrest: 1.3.2
  provider: 6.0.4
  realtime_client: 1.1.1
  rxdart: 0.27.7
  shared_preferences: 2.0.15
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  sign_in_with_apple: 4.3.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  sqflite: 2.2.6
  storage_client: 1.5.1
  stream_transform: 2.1.0
  supabase: 1.6.3
  supabase_flutter: 1.7.0
  timeago: 3.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  video_player: 2.6.0
  video_player_android: 2.4.3
  video_player_avfoundation: 2.4.2
  video_player_platform_interface: 6.1.0
  video_player_web: 2.0.15
  webview_flutter: 4.0.5
  webview_flutter_android: 3.3.1
  webview_flutter_platform_interface: 2.0.2
  webview_flutter_wkwebview: 3.1.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  rxdart: 0.27.7

dev_dependencies:

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
